name: Release Workflow

on:
  release:
    types: [published]
  push:
    paths:
      - 'requirements.txt'

jobs:
  fetch_and_unzip:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download release asset
      run: |
        $ReleaseId = $env:GITHUB_REF_NAME
        $Repo = $env:GITHUB_REPOSITORY
        $Token = $env:GITHUB_TOKEN

        # Fetch release information
        $Release = Invoke-RestMethod -Headers @{ Authorization = "token $Token" } -Uri "https://api.github.com/repos/$Repo/releases/tags/$ReleaseId"

        # Find the asset by name
        $Asset = $Release.assets | Where-Object { $_.name -eq "Aark_Host_Simulator-Version-1.00.00.0006.exe.zip" }
        if (-not $Asset) { throw "Asset not found" }

        # Download the asset
        Invoke-RestMethod -Headers @{ Authorization = "token $Token"; Accept = "application/octet-stream" } -Uri $Asset.url -OutFile "release.zip"

    - name: Print current directory path
      run: echo "Current directory:%cd%"

    - name: Unzip release asset
      run: powershell -Command "Expand-Archive -Path ./release.zip -DestinationPath ./release"

    - name: Print contents of unzipped directory
      run: dir ./release
