name: Release Pipeline

on:
  release:
    types:
      - published  # Trigger when a release is published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x  # Adjust the .NET version if needed

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal

    - name: Publish output
      run: dotnet publish --configuration Release --no-restore --output ./output

    - name: Archive build output
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: ./output

    - name: Fetch and unzip artifact
      run: |
        echo "Fetching artifact..."
        if [ -z "${{ steps.upload-artifact.outputs.artifact-id }}" ]; then
          echo "Artifact ID is undefined"
          exit 1
        fi
        artifact_id=${{ steps.upload-artifact.outputs.artifact-id }}
        echo "Artifact ID: $artifact_id"
        # Your fetch and unzip logic here

    - name: Create release notes
      run: echo "Release notes for $(date)" > release_notes.txt

    - name: Upload release notes
      uses: actions/upload-artifact@v2
      with:
        name: release-notes
        path: release_notes.txt
