name: Build and Package

on:
  release:
    types: 
      - published

  push:
    paths:
      - main.yml  # Trigger when setup.iss is changed
      

jobs:
  build_package_and_email:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and install Inno Setup
        run: |
         dir cd D:\a\AarkFence-Server-22\
          

          curl -L -o innosetup.exe "https://jrsoftware.org/download.php/is.exe"
          Start-Process -FilePath "innosetup.exe" -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART" -NoNewWindow -Wait


      - name: Dependency folder and making .exe
        run: |
          dir
          tar -xf D:/a/singh/singh/Aark_Host_Simulator-Version-1.00.00.0006.exe
          
          mkdir  D:/a/singh/singh/\Dependencyfolder
          
          
          dir D:/a/singh/singh/
          dir  D:/a/singh/singh/\Dependencyfolder
          move D:/a/singh/singh/\assessment_reports  D:\a\AarkFence-Server-22\AarkFence-Server-22\Dependencyfolder
          
          


      - name: Run Inno Setup compiler
        run: |
          Start-Process -FilePath "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" -ArgumentList "Devops/setupscript22.iss" -NoNewWindow -Wait

      - name: Print current directory contents
        run: |
          dir

      - name: Print current directory contents
        run: |
          dir D:/a/singh/singh/Devops

      - name: Print current directory contents
        run: |
          dir       
          dir D:/a/singh/singh/

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Upload Inno Setup installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: AHS-Setup_exe
          path: D:/a/singh/singh/setup # Adjust path to setup.exe output file
