name: Release Workflow

on:
  release:
    types: [published]
  push:
    paths:
      - 'requirements.txt'

jobs:
  fetch_and_unzip:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download release asset
      uses: actions/github-script@v6
      id: download-release-asset
      with:
        script: |
          const fs = require('fs');
          const { owner, repo } = context.repo;
          const release_id = context.payload.release.id;
          const asset_name = 'Aark_Host_Simulator-Version-1.00.00.0006.exe.zip';
          
          const { data: assets } = await github.repos.listReleaseAssets({
            owner,
            repo,
            release_id
          });

          const asset = assets.find(a => a.name === asset_name);
          
          if (!asset) {
            throw new Error(`Asset ${asset_name} not found in release`);
          }

          const { data: assetData } = await github.repos.getReleaseAsset({
            owner,
            repo,
            asset_id: asset.id,
            headers: {
              accept: 'application/octet-stream'
            }
          });

          fs.writeFileSync('./release.zip', Buffer.from(assetData));

    - name: Print current directory path
      run: echo "Current directory:%cd%"

    - name: Unzip release asset
      run: powershell -Command "Expand-Archive -Path ./release.zip -DestinationPath ./release"

    - name: Print contents of unzipped directory
      run: dir ./release
