name: Build and Package

on:
  release:
    types:  
      - published

  push:
    paths:
      - requirements.txt # Trigger when setup.iss is changed

jobs:
  build_package_and_email:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure the entire history is fetched to access the release

      - name: Download release artifact
        run: |
          dir
          pwd
          mkdir kp
          dir kp
