name: Release Workflow

on:
  release:
    types: [published]
  push:
    paths:
      - 'requirements.txt'

jobs:
  fetch_and_unzip:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download release asset
      id: download-release-asset
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const { data: release } = await github.repos.getReleaseByTag({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag: context.payload.release.tag_name,
          });
          const asset = release.assets.find(asset => asset.name === 'Aark_Host_Simulator-Version-1.00.00.0006.exe.zip');
          const download = await github.repos.getReleaseAsset({
            owner: context.repo.owner,
            repo: context.repo.repo,
            asset_id: asset.id,
            headers: {
              accept: 'application/octet-stream',
            },
          });
          fs.writeFileSync('./release.zip', Buffer.from(download.data));

    - name: Print current directory path
      run: echo "Current directory:%cd%"

    - name: Unzip release asset
      run: powershell -Command "Expand-Archive -Path ./release.zip -DestinationPath ./release"

    - name: Print contents of unzipped directory
      run: dir ./release
