name: Build and Package Application

on:
  push:
    branches:
      - main  # Adjust branch name as per your main branch

jobs:
  build_age_cal_exe:
    runs-on: windows-latest  # Use windows-latest for Windows instance
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Replace with your Python version
        
    - name: Install dependencies
      run: |
        dir
        pip install pyinstaller
        
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
        
    - name: Build executable
      run: |
        dir
        pyinstaller --onefile age_cal.py  # Adjust path as needed
        
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: age_cal_exe
        path: dist/age_cal.exe

  build_inno_setup:
    runs-on: windows-latest  # Use windows-latest for Windows instance
    needs: build_age_cal_exe  # Ensure this job runs after build_age_cal_exe job
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
        
    - name: Download age_cal.exe artifact
      uses: actions/download-artifact@v2
      with:
        name: age_cal_exe
        path: dist/age_cal.exe  # Specify the path where age_cal.exe should be downloaded
        
    - name: Download Inno Setup
      run: |
        curl -L -o innosetup.exe "https://jrsoftware.org/download.php/is.exe"
        start /wait innosetup.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
        
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
        
    - name: Create Inno Setup script
      run: |
        dir
        echo "[Setup]
        OutputBaseFilename=setupofapp
        AppVersion=1.0
        DefaultDirName={pf}\newappsetup
        DisableProgramGroupPage=yes
        UninstallDisplayIcon={app}\{#AppName}.exe
        Compression=lzma
        SolidCompression=yes

        [Files]
        Source: dist/age_cal.exe; DestDir: {app}; Flags: ignoreversion
        " > setup_script.iss
        
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
        
    - name: Run Inno Setup compiler
      run: |
        dir
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" setup_script.iss
        
    - name: Print current directory
      run: |
        echo "Current working directory: $PWD"
        dir  # List contents of current directory
        
    - name: Upload Inno Setup installer artifact
      uses: actions/upload-artifact@v2
      with:
        name: setup_exe
        path: dist/age_cal.exe  # Adjust path to setup.exe output file
